In [1]:
import pandas as pd
import numpy as np

In [4]:
train=pd.read_csv("file:///C:/Users/JH729EU/OneDrive - EY/Datascience/Experience/CreditAnalytics-Loan-Prediction/Data/train_u6lujuX_CVtuZ9i.csv")
test=pd.read_csv("file:///C:/Users/JH729EU/OneDrive - EY/Datascience/Experience/CreditAnalytics-Loan-Prediction/Data/test_Y3wMUE5_7gLdaTN.csv")

In [5]:
list(train)

['Loan_ID',
 'Gender',
 'Married',
 'Dependents',
 'Education',
 'Self_Employed',
 'ApplicantIncome',
 'CoapplicantIncome',
 'LoanAmount',
 'Loan_Amount_Term',
 'Credit_History',
 'Property_Area',
 'Loan_Status']

In [6]:
# This part of the code 
# imports all the libraries we need 
# reads the data from the files 
# Lists all the headers 

In [7]:
train.head(10)
train.dtypes
train.describe()

#gains a sample then gets the types of data and then shows this 

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [10]:
train.isnull().sum()
test.isnull().sum()
train.fillna(train.mean(),inplace=True) 
train.isnull().sum() 
test.fillna(test.mean(),inplace=True) 
test.isnull().sum()
#finds the missing values and fills it with the means of the data 


Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term      0
Credit_History        0
Property_Area         0
dtype: int64

In [11]:
train.Gender.fillna(train.Gender.mode()[0],inplace=True)
train.Married.fillna(train.Married.mode()[0],inplace=True)
train.Dependents.fillna(train.Dependents.mode()[0],inplace=True) 
train.Self_Employed.fillna(train.Self_Employed.mode()[0],inplace=True)  
train.isnull().sum() 
test.Gender.fillna(test.Gender.mode()[0],inplace=True)
test.Dependents.fillna(test.Dependents.mode()[0],inplace=True) 
test.Self_Employed.fillna(test.Self_Employed.mode()[0],inplace=True)  
test.isnull().sum() 
train.Loan_Amount_Term=np.log(train.Loan_Amount_Term)

# Code to clean up the data for categorical variables 
# Also treats the outliners of the data 

In [12]:
train=train.drop('Loan_ID',axis=1)
test=test.drop('Loan_ID',axis=1)
X=train.drop('Loan_Status',1)
y=train.Loan_Status
X=pd.get_dummies(X)
train=pd.get_dummies(train)
test=pd.get_dummies(test)
from sklearn.model_selection import train_test_split
x_train,x_cv,y_train,y_cv = train_test_split(X,y,test_size=0.2)

# we now remove the loan_ID variable it is not needed 
#we create a target 
# we use dummy variable for the catogories 
# we then split the data 

In [14]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)
pred_cv=model.predict(x_cv)
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
accuracy_score(y_cv,pred_cv) #78.86%
matrix=confusion_matrix(y_cv,pred_cv)
print(matrix)

# This is the logistics regression algorithm 
#we fit the model 
#predict the models 
#evaluate the accuracy 

[[17 19]
 [ 1 86]]


C:\Users\JH729EU\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [18]:
from sklearn import tree
dt=tree.DecisionTreeClassifier(criterion='gini')
dt.fit(x_train,y_train)
pred_cv1=dt.predict(x_cv)
accuracy_score(y_cv,pred_cv1)
matrix1=confusion_matrix(y_cv,pred_cv1)
print(matrix1)

# This is the decision tree algorithm
#we fit the model 
#predict the models 
#evaluate the accuracy 

[[22 14]
 [29 58]]


In [19]:
#(e)NAIVE BAYES ALGORITHM
from sklearn.naive_bayes import GaussianNB 
nb=GaussianNB()
nb.fit(x_train,y_train)
pred_cv4=nb.predict(x_cv)
accuracy_score(y_cv,pred_cv4) #80.49%
matrix4=confusion_matrix(y_cv,pred_cv4)
print(matrix4)

# This is the naive bayes algorithm
#we fit the model 
#predict the models 
#evaluate the accuracy 

[[18 18]
 [ 4 83]]


In [22]:
#(f)K-NEAREST NEIGHBOR(kNN) ALGORITHM
from sklearn.neighbors import KNeighborsClassifier
kNN=KNeighborsClassifier()
kNN.fit(x_train,y_train)
pred_cv5=kNN.predict(x_cv)
accuracy_score(y_cv,pred_cv5) 
matrix5=confusion_matrix(y_cv,pred_cv5)
print(matrix5)

# This is the kNN K nearest algorithm
#we fit the model 
#predict the models 
#evaluate the accuracy 

[[ 5 31]
 [20 67]]
0.5853658536585366


In [23]:
pred_test=nb.predict(test)
predictions=pd.DataFrame(pred_test, columns=['predictions']).to_csv('Credit_Predictions.csv')


# we then predict the values using test data (naive bayes )
# then we write to the results to a csv file 

In [24]:
##(f)K-NEAREST NEIGHBOR(kNN) ALGORITHM accuracy
print(accuracy_score(y_cv,pred_cv5) )

0.5853658536585366


In [25]:
#decision tree algorithm accuracy
print(accuracy_score(y_cv,pred_cv1) )

0.6504065040650406


In [26]:
#LogisticRegression algorithm accuracy
print(accuracy_score(y_cv,pred_cv) )

0.8373983739837398


In [27]:
#NAIVE BAYES ALGORITHM algorithm accuracy
print(accuracy_score(y_cv,pred_cv) )

0.8373983739837398
